--liquibase formatted sql

--changeset dota-dev:1

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);


ALTER TABLE roles
    ADD CONSTRAINT uk_roles_name UNIQUE (name);


CREATE TABLE heroes
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name              VARCHAR(255) NOT NULL,
    primary_attribute VARCHAR(255) NOT NULL,
    CONSTRAINT pk_heroes PRIMARY KEY (id)
);


ALTER TABLE heroes
    ADD CONSTRAINT uk_heroes_name UNIQUE (name);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nickname VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);


ALTER TABLE users
    ADD CONSTRAINT uk_users_name UNIQUE (nickname);

ALTER TABLE users
    ADD CONSTRAINT uk_users_email UNIQUE (email);


CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
);


ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_role FOREIGN KEY (role_id) REFERENCES roles (id);


CREATE TABLE matches
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    start_time          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    duration_in_seconds INT          NOT NULL,
    winner              VARCHAR(255) NOT NULL,
    CONSTRAINT pk_matches PRIMARY KEY (id)
);

CREATE TABLE match_player_stats
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kills    INT    NOT NULL,
    deaths   INT    NOT NULL,
    assists  INT    NOT NULL,
    match_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    hero_id  BIGINT NOT NULL,
    CONSTRAINT pk_match_player_stats PRIMARY KEY (id)
);


ALTER TABLE match_player_stats
    ADD CONSTRAINT fk_match_player_stats_on_match FOREIGN KEY (match_id) REFERENCES matches (id);

ALTER TABLE match_player_stats
    ADD CONSTRAINT fk_match_player_stats_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE match_player_stats
    ADD CONSTRAINT fk_match_player_stats_on_hero FOREIGN KEY (hero_id) REFERENCES heroes (id);
