--liquibase formatted sql

--changeset dota-dev:3

CREATE TABLE reports
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT       NOT NULL,
    status       VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_reports PRIMARY KEY (id)
);

ALTER TABLE reports
    ADD CONSTRAINT fk_reports_on_user FOREIGN KEY (user_id) REFERENCES users (id);
